<?php
/**
 * Supplemental micro-quiz questions (7 each) to reach ~10 per lesson.
 * Indexed: [week][lesson_index 0-3]
 */

require_once(__DIR__ . '/js_course_week_helpers.php');

return [
    2 => [
        0 => [
            js_mcq('let vs const, mana yang wajib diisi saat deklarasi?', ['let', 'const', 'keduanya tidak', 'var saja'], 1, 'const harus diinisialisasi saat deklarasi.'),
            js_mcq('Nama variabel baik untuk jumlah siswa?', ['x', 'a', 'jumlahSiswa', '123jumlah'], 2, 'Gunakan nama deskriptif camelCase.'),
            js_mcq('var termasuk?', ['Cara lama (legacy)', 'ES6 only', 'Hanya server', 'Tidak ada di JS'], 0, 'var adalah deklarasi lama.'),
            js_mcq('let skor = 90; skor = 95 valid?', ['Ya', 'Tidak', 'Error selalu', 'Hanya const'], 0, 'let boleh di-reassign.'),
            js_mcq('Deklarasi sebelum digunakan?', ['Disarankan', 'Tidak perlu', 'Dilarang', 'Hanya di Python'], 0, 'Variabel harus dideklarasikan dulu.'),
            js_mcq('Simbol $ dalam identifier?', ['Diperbolehkan', 'Dilarang', 'Hanya PHP', 'Error'], 0, '$ boleh di awal identifier.'),
            js_mcq('const NIS = "123"; NIS = "456"?', ['Valid', 'Error', 'Menjadi 123456', 'Null'], 1, 'const tidak bisa di-reassign.'),
        ],
        1 => [
            js_mcq('typeof "hello"?', ['string', 'number', 'boolean', 'object'], 0, 'Teks dalam petik adalah string.'),
            js_mcq('Template literal pakai?', ['Backtick', 'Hanya petik ganda', '@', '#'], 0, 'Backtick untuk `${}` interpolation.'),
            js_mcq('"JavaScript".length?', ['9', '10', '11', '0'], 1, '10 karakter.'),
            js_mcq('String + number jika string dulu?', ['Concatenation', 'Selalu tambah matematika', 'Error', 'Boolean'], 0, '"10"+5 = "105".'),
            js_mcq('toUpperCase() pada string?', ['Ubah huruf besar', 'Ubah number', 'Hapus string', 'Loop'], 0, 'Method string untuk uppercase.'),
            js_mcq('trim() berguna untuk?', ['Hapus spasi ujung', 'Hapus array', 'Sort', 'Split'], 0, 'trim membersihkan whitespace.'),
            js_mcq('String kosong "" falsy?', ['Ya', 'Tidak', 'Hanya null', 'Hanya 0'], 0, '"" adalah falsy.'),
        ],
        2 => [
            js_mcq('typeof 17?', ['number', 'string', 'boolean', 'undefined'], 0, '17 tanpa petik adalah number.'),
            js_mcq('10 / 4 hasil?', ['2.5', '2', '3', '40'], 0, 'Pembagian bisa desimal.'),
            js_mcq('Number("25")?', ['25', '"25"', 'NaN', 'Error'], 0, 'Konversi string angka ke number.'),
            js_mcq('2 ** 3 = ?', ['6', '8', '9', '5'], 1, '2 pangkat 3 = 8.'),
            js_mcq('NaN artinya?', ['Not a Number', 'Null and None', 'New and Number', 'Never a Num'], 0, 'Hasil operasi invalid.'),
            js_mcq('Angka desimal 88.5 valid?', ['Ya', 'Tidak', 'Hanya integer', 'Hanya string'], 0, 'JS number mencakup desimal.'),
            js_mcq('10 + 5 tanpa petik?', ['15', '"105"', '105', 'Error'], 0, 'Penjumlahan numerik.'),
        ],
        3 => [
            js_mcq('Boolean hanya?', ['true/false', '0/1 saja', 'yes/no string', 'on/off string'], 0, 'Nilai boolean true atau false.'),
            js_mcq('null artinya?', ['Sengaja kosong', 'Belum diisi', 'Error', 'String kosong'], 0, 'null = intentionally empty.'),
            js_mcq('let x; console.log(x)?', ['undefined', 'null', '0', 'false'], 0, 'Belum diisi = undefined.'),
            js_mcq('Boolean(0)?', ['false', 'true', '0', 'null'], 0, '0 adalah falsy.'),
            js_mcq('typeof true?', ['boolean', 'string', 'number', 'object'], 0, 'true bertipe boolean.'),
            js_mcq('10 > 5 hasil?', ['true', 'false', '5', '10'], 0, 'Perbandingan menghasilkan boolean.'),
            js_mcq('null === undefined?', ['false', 'true', 'null', 'error'], 0, 'Strict equal: tipe berbeda.'),
        ],
    ],
    3 => [
        0 => [
            js_mcq('17 % 5?', ['2', '3', '3.4', '0'], 0, 'Sisa bagi 17/5 = 2.'),
            js_mcq('Operator pangkat ES6?', ['**', '^', 'pow only', '%%'], 0, '** untuk eksponen.'),
            js_mcq('(10+5)*2?', ['30', '17', '25', '20'], 0, 'Kurung dulu.'),
            js_mcq('5 * 0?', ['0', '5', 'Error', '50'], 0, 'Kali nol = 0.'),
            js_mcq('-5 + 3?', ['-2', '2', '-8', '8'], 0, 'Penjumlahan negatif.'),
            js_mcq('100 % 10?', ['0', '10', '1', '100'], 0, 'Habis dibagi, sisa 0.'),
            js_mcq('% disebut juga?', ['Modulo', 'Modem', 'Module', 'Model'], 0, 'Modulo = sisa bagi.'),
        ],
        1 => [
            js_mcq('5 === "5"?', ['false', 'true', '5', 'Error'], 0, '=== strict: tipe harus sama.'),
            js_mcq('true && false?', ['false', 'true', 'null', '1'], 0, 'AND: salah satu false → false.'),
            js_mcq('true || false?', ['true', 'false', '0', 'null'], 0, 'OR: salah satu true → true.'),
            js_mcq('!true?', ['false', 'true', '0', 'undefined'], 0, 'NOT membalik boolean.'),
            js_mcq('Operator DAN?', ['&&', '||', '!', '=='], 0, '&& = AND.'),
            js_mcq('10 >= 10?', ['true', 'false', '10', 'Error'], 0, '10 sama dengan 10.'),
            js_mcq('=== lebih aman dari == karena?', ['Cek tipe + nilai', 'Lebih cepat', 'Hanya string', 'Tidak ada beda'], 0, '=== strict equality.'),
        ],
        2 => [
            js_mcq('prompt() return tipe?', ['string', 'number', 'boolean', 'object'], 0, 'prompt selalu string.'),
            js_mcq('prompt() untuk?', ['Input user', 'Output file', 'Loop', 'CSS'], 0, 'Dialog input browser.'),
            js_mcq('Cancel prompt bisa return?', ['null', '0', 'undefined selalu', 'false'], 0, 'Cancel → null.'),
            js_mcq('Input angka dari prompt butuh?', ['Number()', 'String() only', 'Boolean()', 'Array()'], 0, 'Konversi eksplisit.'),
            js_mcq('prompt() berjalan di?', ['Browser', 'MySQL', 'PHP only', 'BIOS'], 0, 'Browser API.'),
            js_mcq('Gabung prompt + string pakai?', ['+', '-', '/', '%'], 0, 'Concatenation dengan +.'),
            js_mcq('prompt termasuk?', ['Browser API', 'CSS', 'HTML tag', 'SQL'], 0, 'Bagian Web API.'),
        ],
        3 => [
            js_mcq('Number("abc")?', ['NaN', '0', '"abc"', 'false'], 0, 'Tidak bisa konversi → NaN.'),
            js_mcq('parseInt("42px")?', ['42', 'NaN', '"42"', '42px'], 0, 'parseInt ambil angka awal.'),
            js_mcq('String(100)?', ['"100"', '100', 'true', 'number'], 0, 'Konversi ke string.'),
            js_mcq('Boolean("")?', ['false', 'true', '""', 'null'], 0, 'String kosong falsy.'),
            js_mcq('"10" - 5?', ['5', '"105"', 'NaN', '15'], 0, 'Minus memaksa number: 5.'),
            js_mcq('Konversi eksplisit artinya?', ['Sengaja convert', 'Otomatis selalu', 'Tidak perlu', 'Error'], 0, 'Eksplisit = programmer yang convert.'),
            js_mcq('typeof Number("5")?', ['number', 'string', 'boolean', 'object'], 0, 'Hasil Number() bertipe number.'),
        ],
    ],
    4 => [
        0 => [
            js_mcq('if mengecek?', ['Kondisi true/false', 'Loop', 'Array', 'CSS'], 0, 'if = percabangan kondisi.'),
            js_mcq('if (false) body dijalankan?', ['Tidak', 'Ya', 'Dua kali', 'Error'], 0, 'Hanya true yang jalan.'),
            js_mcq('Kondisi dalam?', ['Kurung ()', 'Kurung []', 'Petik', 'Angle <>'], 0, 'if (kondisi).'),
            js_mcq('if termasuk struktur?', ['Kontrol', 'Data', 'Tipe', 'Markup'], 0, 'Control structure.'),
            js_mcq('if (nilai >= 75) cek?', ['Lebih sama 75', 'Kurang 75', 'Sama string', 'Array'], 0, '>= artinya minimal 75.'),
            js_mcq('Blok if ditulis dalam?', ['{}', '[]', '()', '<>'], 0, 'Curly braces.'),
            js_mcq('if tanpa {} untuk 1 statement?', ['Boleh', 'Tidak boleh', 'Error', 'Wajib 3 baris'], 0, 'Single statement boleh tanpa block.'),
        ],
        1 => [
            js_mcq('else jika if false?', ['Jalankan else', 'Skip semua', 'Loop', 'Return'], 0, 'else = alternatif.'),
            js_mcq('else if untuk?', ['Banyak kondisi', 'Satu kondisi', 'Loop', 'Array'], 0, 'Rantai kondisi.'),
            js_mcq('else wajib?', ['Tidak', 'Ya selalu', 'Hanya switch', 'Hanya for'], 0, 'else opsional.'),
            js_mcq('Hanya satu blok jalan di if-else?', ['Ya', 'Tidak semua', 'Dua sekaligus', 'Tiga'], 0, 'Mutually exclusive.'),
            js_mcq('else if (skor >= 60) artinya?', ['Minimal 60', 'Kurang 60', 'Sama 60 saja', 'String'], 0, '>= 60.'),
            js_mcq('if-else bisa nested?', ['Ya', 'Tidak', 'Hanya Python', 'Hanya Java'], 0, 'if dalam if valid.'),
            js_mcq('else catch-all untuk?', ['Kondisi lain', 'Error', 'Loop', 'Function'], 0, 'Default branch.'),
        ],
        2 => [
            js_mcq('switch cocok untuk?', ['Nilai tetap banyak', 'Loop', 'Function', 'CSS'], 0, 'Multi-case value matching.'),
            js_mcq('break di switch?', ['Stop case', 'Lanjut', 'Loop', 'Return nilai'], 0, 'break keluar dari switch.'),
            js_mcq('default = ?', ['Case lain', 'Error', 'Wajib selalu', 'Loop'], 0, 'Fallback case.'),
            js_mcq('switch tanpa break bisa?', ['Fall-through', 'Error', 'Stop', 'Restart'], 0, 'Jatuh ke case berikut.'),
            js_mcq('case 1: artinya nilai switch?', ['1', '>1', '<1', 'true'], 0, 'Match nilai 1.'),
            js_mcq('default biasanya di?', ['Akhir', 'Awal', 'Tengah', 'Tidak ada'], 0, 'Konvensi di akhir.'),
            js_mcq('switch pakai kurung?', ['()', '[]', '{}', '<>'], 0, 'switch(expr).'),
        ],
        3 => [
            js_mcq('Nested if?', ['if dalam if', 'if dalam for saja', 'for dalam CSS', 'switch dalam HTML'], 0, 'If di dalam if.'),
            js_mcq('&& artinya?', ['DAN', 'ATAU', 'NOT', 'XOR'], 0, 'Logical AND.'),
            js_mcq('|| artinya?', ['ATAU', 'DAN', 'NOT', 'IF'], 0, 'Logical OR.'),
            js_mcq('(5>3)||(2>10)?', ['true', 'false', '0', 'error'], 0, 'Salah satu true → true.'),
            js_mcq('(5>3)&&(2>10)?', ['false', 'true', '1', 'null'], 0, 'Keduanya harus true.'),
            js_mcq('!hadir jika hadir=false?', ['true', 'false', 'null', '0'], 0, 'NOT false = true.'),
            js_mcq('Gabung kondisi tanpa nested?', ['&& ||', 'for', 'prompt', 'alert'], 0, 'Operator logika.'),
        ],
    ],
    5 => [
        0 => [
            js_mcq('for: init; kondisi; increment?', ['Benar', 'Salah', 'Hanya while', 'Hanya do'], 0, 'Struktur for standar.'),
            js_mcq('i++ sama dengan?', ['i=i+1', 'i+1', 'i--', 'i*2'], 0, 'Increment.'),
            js_mcq('for i=1;i<=3 iterasi?', ['3', '2', '4', '1'], 0, 'Tiga kali loop.'),
            js_mcq('for cocok jika?', ['Iterasi diketahui', 'Tidak pernah', 'Hanya string', 'Hanya CSS'], 0, 'Known iteration count.'),
            js_mcq('Infinite loop jika kondisi?', ['Selalu true', 'Selalu false', 'Sekali', 'Never'], 0, 'true forever → infinite.'),
            js_mcq('i+=2 artinya?', ['Naik 2', 'Turun 2', 'Kali 2', 'Bagi 2'], 0, 'Step increment 2.'),
            js_mcq('for loop array index?', ['Cocok', 'Tidak bisa', 'Hanya object', 'Hanya CSS'], 0, 'Classic for + index.'),
        ],
        1 => [
            js_mcq('while cek kondisi?', ['Sebelum body', 'Sesudah', 'Tidak pernah', 'Di tengah'], 0, 'Pre-test loop.'),
            js_mcq('while(false) iterasi?', ['0', '1', '2', 'Infinite'], 0, 'Tidak masuk body.'),
            js_mcq('Counter while perlu?', ['Increment manual', 'Otomatis', 'Tidak perlu', 'Hanya for'], 0, 'Update variabel counter.'),
            js_mcq('while(true)?', ['Infinite loop', 'Stop', 'Error', 'Once'], 0, 'Selalu true.'),
            js_mcq('while vs for, for lebih?', ['Terstruktur', 'Selalu lambat', 'Invalid', 'CSS'], 0, 'for lebih terstruktur.'),
            js_mcq('while minimal iterasi jika false?', ['0', '1', '2', '3'], 0, 'Tidak jalan sama sekali.'),
            js_mcq('while cocok jika?', ['Iterasi tidak pasti', 'Selalu 10x', 'Tidak pernah', 'Hanya array'], 0, 'Unknown iterations.'),
        ],
        2 => [
            js_mcq('do-while cek?', ['Sesudah body', 'Sebelum', 'Tidak', 'Tengah'], 0, 'Post-test loop.'),
            js_mcq('do-while minimal?', ['1 kali', '0 kali', '2 kali', 'Tidak pernah'], 0, 'Minimal satu eksekusi.'),
            js_mcq('do-while(false) jalan?', ['1 kali', '0 kali', 'Infinite', 'Error'], 0, 'Body jalan dulu.'),
            js_mcq('Semicolon setelah while?', ['Wajib', 'Dilarang', 'Opsional saja Python', 'Error'], 0, 'do{}while();'),
            js_mcq('do-while vs while?', ['Timing cek', 'Tidak ada beda', 'Hanya string', 'Hanya for'], 0, 'When condition checked.'),
            js_mcq('do-while termasuk?', ['Loop', 'Function', 'Operator', 'Tipe'], 0, 'Loop structure.'),
            js_mcq('do {} while (x<3) minimal?', ['1x eksekusi', '0x', '2x wajib', 'Error'], 0, 'At least once.'),
        ],
        3 => [
            js_mcq('break?', ['Stop loop', 'Skip iterasi', 'Lanjut', 'Restart'], 0, 'Keluar dari loop.'),
            js_mcq('continue?', ['Skip iterasi ini', 'Stop all', 'Error', 'Return'], 0, 'Loncat ke iterasi berikut.'),
            js_mcq('break di switch juga?', ['Ya', 'Tidak', 'Hanya for', 'Hanya while'], 0, 'break di switch & loop.'),
            js_mcq('continue skip?', ['Iterasi saat ini', 'Seluruh program', 'Function', 'Variable'], 0, 'Current iteration only.'),
            js_mcq('Loop ganjil 1-10 pakai continue genap?', ['Ya', 'Tidak', 'Hanya break', 'Hanya if'], 0, 'skip even → print odd.'),
            js_mcq('break vs return?', ['return keluar function', 'Sama', 'break keluar function', 'Tidak ada beda'], 0, 'return = exit function.'),
            js_mcq('break di for i=5 stop di?', ['5', '10', '1', '0'], 0, 'Stop saat i=5.'),
        ],
    ],
    6 => [
        0 => [
            js_mcq('function reusable?', ['Ya', 'Tidak', 'Hanya sekali', 'Hanya CSS'], 0, 'Bisa dipanggil berulang.'),
            js_mcq('addEventListener untuk?', ['Event handler', 'Loop', 'Array', 'CSS file'], 0, 'Pasang listener event.'),
            js_mcq('getElementById butuh?', ['id', 'class', 'tag', 'name'], 0, 'Select by id.'),
            js_mcq('DOM?', ['Representasi HTML di JS', 'Database', 'CSS', 'PHP'], 0, 'Document Object Model.'),
            js_mcq('Event click?', ['Klik mouse', 'Ketik', 'Scroll', 'Load only'], 0, 'Mouse click event.'),
            js_mcq('textContent vs innerHTML, teks aman?', ['textContent', 'innerHTML', 'Sama', 'Tidak ada'], 0, 'textContent untuk teks.'),
            js_mcq('Function dipanggil?', ['nama()', 'call nama', 'function nama', 'return nama'], 0, 'Call syntax.'),
        ],
        1 => [
            js_mcq('return function?', ['Kirim nilai balik', 'Stop browser', 'Loop', 'CSS'], 0, 'Return value.'),
            js_mcq('Parameter = ?', ['Input function', 'Output', 'Loop', 'Event'], 0, 'Input ke function.'),
            js_mcq('Number() pada input value?', ['Konversi ke angka', 'Hapus input', 'Sort', 'Filter'], 0, 'String → number.'),
            js_mcq('dataset pada button?', ['Data attribute', 'CSS', 'HTML tag', 'SQL'], 0, 'data-* attributes.'),
            js_mcq('Arrow function syntax?', ['() => {}', 'function=>', '-> {}', 'def ()'], 0, 'ES6 arrow.'),
            js_mcq('Callback function?', ['Dikirim ke function lain', 'Hanya global', 'Hanya loop', 'Hanya CSS'], 0, 'Function as argument.'),
            js_mcq('tambah(5,3) return 8?', ['Penjumlahan', 'Concatenation', 'Error', '53'], 0, '5+3=8.'),
        ],
        2 => [
            js_mcq('click counter perlu?', ['Variabel count', 'Tanpa variabel', 'Hanya CSS', 'Hanya HTML'], 0, 'State counter.'),
            js_mcq('addEventListener("click") saat?', ['Tombol diklik', 'Page load', 'Error', 'Blur'], 0, 'On click.'),
            js_mcq('Multiple listener 1 element?', ['Bisa', 'Tidak', 'Error', 'Hanya 1'], 0, 'Bisa banyak listener.'),
            js_mcq('preventDefault?', ['Cegah aksi default', 'Loop', 'Array', 'Console'], 0, 'Stop default behavior.'),
            js_mcq('DOMContentLoaded saat?', ['HTML siap', 'Never', 'CSS only', 'PHP'], 0, 'DOM ready.'),
            js_mcq('Event handler = ?', ['Fungsi respons event', 'Loop', 'Tipe data', 'CSS'], 0, 'Handler callback.'),
            js_mcq('getElementById return?', ['Element atau null', 'Selalu string', 'Number', 'Array always'], 0, 'DOM element reference.'),
        ],
        3 => [
            js_mcq('Event input saat?', ['User mengetik', 'Klik', 'Submit form', 'Close'], 0, 'On typing.'),
            js_mcq('this.value di input?', ['Nilai input', 'Id', 'Class', 'Loop'], 0, 'Current input value.'),
            js_mcq('Live preview nama pakai?', ['input event', 'click only', 'dblclick', 'load only'], 0, 'Real-time on input.'),
            js_mcq('Manipulasi DOM?', ['Ubah HTML via JS', 'Hanya CSS', 'Hanya PHP', 'Tanpa JS'], 0, 'JS changes DOM.'),
            js_mcq('querySelector?', ['CSS selector', 'Id only', 'Tag only', 'Error'], 0, 'Flexible selector.'),
            js_mcq('element.style.color?', ['Inline style', 'External CSS file', 'Database', 'PHP'], 0, 'JS inline styling.'),
            js_mcq('document root DOM?', ['document', 'window only', 'console', 'body only'], 0, 'document object.'),
        ],
    ],
    7 => [
        0 => [
            js_mcq('Array indeks mulai?', ['0', '1', '-1', '2'], 0, 'Zero-indexed.'),
            js_mcq('push() menambah di?', ['Akhir', 'Awal', 'Tengah', 'Hapus'], 0, 'Append to end.'),
            js_mcq('forEach untuk?', ['Loop array', 'Loop object only', 'CSS', 'PHP'], 0, 'Iterate array.'),
            js_mcq('[1,2,3].length?', ['3', '2', '1', '0'], 0, 'Three elements.'),
            js_mcq('createElement("li")?', ['Buat list item', 'Buat row', 'Buat form', 'Buat link'], 0, 'LI element.'),
            js_mcq('appendChild?', ['Tambah child DOM', 'Hapus', 'Sort', 'Filter'], 0, 'Add child node.'),
            js_mcq('Array literal syntax?', ['[]', '{}', '()', '<>'], 0, 'Square brackets.'),
        ],
        1 => [
            js_mcq('Object syntax?', ['{}', '[]', '()', '<>'], 0, 'Curly braces.'),
            js_mcq('siswa.nama akses?', ['Dot notation', 'Hanya []', 'Error', 'CSS'], 0, 'Property access.'),
            js_mcq('Object key-value?', ['Ya', 'Tidak', 'Hanya index', 'Hanya CSS'], 0, 'Key-value pairs.'),
            js_mcq('typeof {}?', ['object', 'array', 'function', 'string'], 0, 'Objects typeof object.'),
            js_mcq('JSON mirip?', ['Object notation', 'CSS', 'HTML', 'PHP'], 0, 'JSON based on objects.'),
            js_mcq('Object nested?', ['Bisa', 'Tidak', 'Error', 'Hanya array'], 0, 'Nested objects valid.'),
            js_mcq('siswa["nama"]?', ['Bracket notation', 'Error', 'Dot only', 'Loop'], 0, 'Bracket access.'),
        ],
        2 => [
            js_mcq('getElementById("#x") salah karena?', ['Tidak pakai #', 'Wajib *', 'Wajib .', 'Error JS'], 0, 'getElementById tanpa #.'),
            js_mcq('querySelector("#x") # artinya?', ['Id', 'Class', 'Tag', 'Attr'], 0, 'CSS id selector.'),
            js_mcq('querySelector(".btn") . artinya?', ['Class', 'Id', 'Tag', 'Pseudo'], 0, 'Class selector.'),
            js_mcq('null jika element tidak ada?', ['Bisa', 'Tidak pernah', 'Error always', 'true'], 0, 'Returns null.'),
            js_mcq('id harus unik?', ['Ya di halaman', 'Tidak', 'Tidak perlu', 'Hanya class'], 0, 'Unique id per page.'),
            js_mcq('textContent ubah?', ['Teks elemen', 'HTML parse', 'CSS file', 'Database'], 0, 'Text only update.'),
            js_mcq('style.color = "red"?', ['Inline style', 'External', 'PHP', 'SQL'], 0, 'JS inline CSS.'),
        ],
        3 => [
            js_mcq('createElement("tr")?', ['Table row', 'Div', 'Input', 'Link'], 0, 'TR element.'),
            js_mcq('innerHTML set?', ['HTML string', 'Only text always', 'Number', 'Boolean'], 0, 'Parse HTML string.'),
            js_mcq('Array of objects ke tabel?', ['Loop + createElement', 'Hanya CSS', 'Tanpa JS', 'PHP only'], 0, 'Dynamic rows.'),
            js_mcq('tbody target untuk?', ['Table body', 'Form', 'Input', 'CSS'], 0, 'Table body section.'),
            js_mcq('Render ulang setelah data change?', ['Perlu update DOM', 'Otomatis always', 'Tidak perlu', 'Error'], 0, 'Re-render DOM.'),
            js_mcq('tr.innerHTML td?', ['Valid', 'Invalid', 'Error', 'Hanya th'], 0, 'Set cell HTML.'),
            js_mcq('Dynamic row artinya?', ['Dibuat JS', 'Static HTML only', 'PHP', 'Database'], 0, 'JS-generated.'),
        ],
    ],
    8 => [
        0 => [
            js_mcq('Opsi project berapa?', ['3', '1', '10', '0'], 0, 'Kalkulator, Todo, Kasir.'),
            js_mcq('Pseudocode tujuan?', ['Rencana logika', 'Desain logo', 'Database', 'PHP'], 0, 'Plan before code.'),
            js_mcq('Testing sebelum submit?', ['Penting', 'Tidak perlu', 'Hanya guru', 'Hanya CSS'], 0, 'Always test.'),
            js_mcq('Final project mode?', ['Ujian', 'Latihan only', 'Page', 'Quiz'], 0, 'Aicode exam mode.'),
            js_mcq('Bobot final project?', ['30%', '10%', '5%', '50%'], 0, '30% of course grade.'),
            js_mcq('Array untuk todo?', ['Ya', 'Tidak', 'Hanya string', 'Hanya number'], 0, 'List of tasks.'),
            js_mcq('Pisahkan data dan render?', ['Best practice', 'Tidak perlu', 'Error', 'Hanya CSS'], 0, 'Separation of concerns.'),
        ],
        1 => [
            js_mcq('Semantic HTML contoh?', ['header, main', 'div only', 'meta only', 'link only'], 0, 'Meaningful tags.'),
            js_mcq('class untuk?', ['Styling grup', 'Loop', 'Array', 'SQL'], 0, 'CSS class hooks.'),
            js_mcq('list-style: none?', ['Hapus bullet', 'Add bullet', 'Loop', 'Error'], 0, 'Unstyled list.'),
            js_mcq('placeholder input?', ['Petunjuk user', 'Submit', 'Loop', 'Data'], 0, 'Hint text.'),
            js_mcq('Flexbox input-group?', ['Layout horizontal', 'Database', 'Loop', 'PHP'], 0, 'Flex row layout.'),
            js_mcq('ul untuk todo list?', ['Cocok', 'Tidak', 'Hanya table', 'Hanya form'], 0, 'List structure.'),
            js_mcq('Responsive max-width?', ['Batas lebar', 'Loop', 'Array', 'SQL'], 0, 'Max container width.'),
        ],
        2 => [
            js_mcq('splice() untuk?', ['Hapus/ubah array', 'CSS', 'HTML', 'SQL'], 0, 'Array mutation.'),
            js_mcq('keypress Enter?', ['Shortcut submit', 'Hapus data', 'Error', 'CSS'], 0, 'UX enhancement.'),
            js_mcq('dataset.i pada hapus?', ['Index item', 'Warna', 'Font', 'URL'], 0, 'Store index.'),
            js_mcq('Re-render setelah push?', ['Panggil render()', 'Tidak perlu', 'Auto always', 'Error'], 0, 'Update DOM.'),
            js_mcq('Guard clause input kosong?', ['if return early', 'Selalu push', 'alert wajib', 'throw'], 0, 'Early return.'),
            js_mcq('Debug project?', ['console.log', 'alert only', 'PHP', 'MySQL'], 0, 'Console debugging.'),
            js_mcq('Event delegation berguna?', ['List dinamis', 'Tidak pernah', 'Error', 'CSS'], 0, 'Dynamic lists.'),
        ],
        3 => [
            js_mcq('Checklist sebelum submit?', ['Semua fitur jalan', 'Tidak perlu', '1 fitur saja', 'CSS saja'], 0, 'Full feature test.'),
            js_mcq('Uji hapus item?', ['Wajib jika ada fitur', 'Tidak', 'Error', 'Hanya add'], 0, 'Test delete.'),
            js_mcq('Uji input kosong?', ['Wajib', 'Tidak', 'Error', 'Guru saja'], 0, 'Edge case.'),
            js_mcq('Submit via?', ['Aicode Ujian', 'Email', 'Kertas', 'WA'], 0, 'Moodle activity.'),
            js_mcq('Bug fix minimal?', ['1 bug', '0 wajib', '100', 'Tidak perlu'], 0, 'Practice debugging.'),
            js_mcq('UI rapi termasuk?', ['Spacing readable', 'Raw only', 'No CSS', 'Error'], 0, 'Usable UI.'),
            js_mcq('Lulus course setelah?', ['Project + grade OK', 'Login saja', 'Buka Moodle', 'CSS'], 0, 'Completion criteria.'),
        ],
    ],
];
